---
title: "Absolute tuber analysis"
author: "Max Miao"
date: "October 9, 2019"
output: html_document
---

```{r setup, include=FALSE}
library(readr)
library(MASS)
library(car)
library(ggplot2)
library(lme4)
library(lmerTest)
library(lsmeans)
```

#Biomass
```{r cars}
meta_data_GH2017 <- read.csv("tuber_analysis_2.csv", header = T)
e_data <- subset(meta_data_GH2017, subset = (Clade == "E"))
str(e_data)
plot(e_data$Clade, e_data$)
e_check1 <- lm(e_data$Biomass_shoots ~ e_data$Variety, e_data)
plot(e_check1)

a_data <- subset(meta_data_GH2017, subset = (Clade == "A"))
plot(a_data$Variety, a_data$Biomass_shoots)

c_data <- subset(meta_data_GH2017, subset = (Clade == "C"))
str(c_data)
plot(c_data$Variety, c_data$Biomass_shoots)

sb_data <- subset(meta_data_GH2017, subset = (Clade == "SB"))
str(sb_data)
plot(sb_data$Variety, sb_data$Biomass_shoots)
```

**mixed model to search for predictors for biomass_shoot**

```{r pressure, echo=FALSE}
labels(meta_data_GH2017)
shootlmer = lmer(Biomass_shoots~Initial_shoot_Length + Nutrient*Soil_type*Species + (1|Species:Variety), data=meta_data_GH2017)
summary(shootlmer)
anova(shootlmer)
lsmeans(shootlmer)
```

#Tuber Mass

**Parse out data** 
```{r}
low_data <- subset(meta_data_GH2017, subset = (Nutrient == "Low"))
tuberlmer = lmer(tuber3 ~ Clade*agerank*soil + (1|variety2), data=low_data)
summary(tuberlmer)
anova(tuberlmer)
lsmeans(tuberlmer, "Clade")

```
```{r}
Virgin_data <- subset(meta_data_GH2017, subset = (soil == "Virgin"))
tuberlmer = lmer(tuber3 ~ Clade*Nutrient*agerank + (1|variety2), data=Virgin_data)
summary(tuberlmer)
anova(tuberlmer)
lsmeans(tuberlmer, "Clade")

```

```{r}
tuberlmer = lmer(tuber3 ~ Clade*Nutrient*agerank*soil + (1|variety2), data=meta_data_GH2017)
summary(tuberlmer)
anova(tuberlmer)
lsmeans(tuberlmer, "Clade")
```

```{r}
a_data <- subset(meta_data_GH2017, subset = (Species== "C"))
almer = lmer(Relsht_avg~Initial_shoot_Length + Nutrient*soil + (1|Clade:Variety), data=a_data)
summary(almer)
anova(almer)
lsmeans(almer)

a_data <- subset(meta_data_GH2017, subset = (Species== "C"))
almer = lmer(Relsht_avg~Initial_shoot_Length + Nutrient*Soil_type + (1|Species:Variety), data=a_data)
summary(almer)
anova(almer)
lsmeans(almer)
```



#plot out data
```{r}
library(ggplot2)
plot_tuber <- ggplot(data = meta_data_GH2017, aes(Clade, tuber3, fill = Nutrient))
plot_tuber + stat_summary(fun.y = mean, geom= "bar", position= "dodge") + stat_summary(fun.data = mean_cl_normal, geom = "errorbar", position = position_dodge(width=0.9), width = 0.2)


```

